version: '3.9'
services:
  order_service:
    build:
      context: ./order_service
    ports:
      - "8000:8000"
    volumes:
      - ./order_service:/app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=order_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
    depends_on:
      - db  # Ensures the database starts before the service

  inventory_service:
    build:
      context: ./inventory_service
    ports:
      - "8001:8000"
    volumes:
      - ./inventory_service:/app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=inventory_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
    depends_on:
      - db  # Ensures the database starts before the service

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: default_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
